version: '3.8'
services:
  client:
    image: weebflix-frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    env_file:
      - ./client/.env
  server-node:
    image: weebflix-backend
    ports:
      - '4001:4001'
    env_file:
      - ./server-node/.env
