version: '3.8'
services:
  api:
    build: ./server-node
    container_name: weebflix_backend
    ports:
      - '4001:4001'
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: weebflix_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
